### ISSUE TITLE
Get Prepared Query

### ISSUE THREAD

**Issue by sushinpv** [kapv89/tabel#5]
Hi, 
I'm using this library for more than 1.5 years now, What i feel, in few cases, using the direct pg is faster, to test that properly and to improve the library, is there any way we can print the prepared query ?

**Comment by kapv89** [comment]
Use `.query().toString()` at the end of your scope-chain. For example:
`table('users').where('id', '>', 5).query().toString()`.

**Comment by kapv89** [comment]
You can also add a `.debug()` to the scope chain to log all the queries(for fetching relationships too) that were ran;
`table('users').where('id', '>', 5).debug().all()`
